### ISSUE TITLE
Question : I do not know why this phrase is visible.

### ISSUE THREAD

**Issue by seungdols** [alrra/dotfiles#28] opened 2016-07-04 11:20 UTC
I install dotfailes program and then i add vim plugin `srcExplToggle` and `TagList`, so, i add in `~/.vimrc` 

```vim
 map <leader>src :SrcExplToggle<CR>                                         
 let g:SrcExpl_winHeight = 8                                              
 let g:SrcExpl_refreshTime = 100                                          
 let g:SrcExpl_jumpKey = "<ENTER>"                                        
 let g:SrcExpl_gobackKey = "<SPACE>"                                      
 let g:SrcExpl_isUpdateTags = 0                                           
                                                                        
 map <leader>tli :Tlist<CR>                                               
 let Tlist_Inc_WinWidth  = 0                                              
 let Tlist_Exit_OnlyWindow = 0                                            
 let Tlist_Auto_Open = 0                                                  
 let Tlist_Use_Right_Window = 1     
```
but i see this the phrases..

```bash
/home/seungdols/.vimrc:1: command not found:  ----------------------------------------------------------------------\n
/home/seungdols/.vimrc:2: command not found: General
/home/seungdols/.vimrc:3: command not found:  ----------------------------------------------------------------------\n\nset nocompatible               
/home/seungdols/.vimrc:25: no matches found: backupskip+=/private/tmp/*
```

What can I tell you that you have the wrong?

**Comment by alrra** [comment] 2016-07-04 11:48
> What can I tell you that you have the wrong?

@seungdols 

* What is the output of `vim --version`?
* Can you provide me with a link to your `.vimrc` file or post its entire content here?

**Comment by alrra** [comment] 2016-07-07 11:04
Closing as I can't reproduce this with only the provided information.

--

@seungdols I'll happily try to help you if you provide further information.

**Closed by alrra** 2016-07-07 11:04 UTC

**Comment by seungdols** [comment] 2016-07-08 01:01
Sorry. I've seen too late.

The installation again, I Enter the following command:

source ~ / .vimrc

And the message coming out is as follows:

```bash
/home/seungdols/.vimrc:1: command not found: ------------------------------------ ---------------------------------- \ n
/home/seungdols/.vimrc:2: command not found: General
/home/seungdols/.vimrc:3: command not found: ------------------------------------ ---------------------------------- \ n \ nset nocompatible
/home/seungdols/.vimrc:25: no matches found: backupskip + = / private / tmp / *
```
```bash
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
포함된 패치: 1-52
```

[.vimrc](https://gist.github.com/seungdols/d43bea19ccf5fd8b85c1b726b5f6dc24)

I'll try again.

**Comment by alrra** [comment] 2016-07-08 06:42
> 
```bash
/home/seungdols/.vimrc:1: command not found: ------------------------------------ ---------------------------------- \ n
/home/seungdols/.vimrc:2: command not found: General
/home/seungdols/.vimrc:3: command not found: ------------------------------------ ---------------------------------- \ n \ nset nocompatible
/home/seungdols/.vimrc:25: no matches found: backupskip + = / private / tmp / *
```

@seungdols That happens because by doing  `source ~/.vimrc`, you're [executing](https://en.wikipedia.org/wiki/Source_(command)) the code from the `~/.vimrc` file using your default shell (e.g. `Bash`).

>  `source ~ / .vimrc`

@seungdols You don't need to source the `~/.vimrc` file, [`Vim` will automatically read and executed that file at startup](http://vimdoc.sourceforge.net/htmldoc/starting.html#vimrc).

-- 

Hope it helps!
